SELECT
    a.ACCIDENT_NO,
    a.ROAD_NAME,
    a.SPEED_ZONE,
    lc.COND_NAME AS LIGHT_CONDITION
FROM Accident AS a
JOIN Light_Condition AS lc
    ON a.LIGHT_CONDITION = lc.COND_ID
LIMIT 20;

SELECT
    a.ACCIDENT_NO,
    a.ROAD_NAME,
    ac.ATMOSPH_COND_DESC AS AMOSPHERIC_CONDITION
FROM Accident AS a
JOIN Atmospheric_Cond_Seq AS acs
    ON a.ACCIDENT_NO = acs.ACCIDENT_NO
JOIN Amospheric_Cond AS ac
    ON acs.ATMOSPH_COND = ac.ATMOSPH_COND
LIMIT 20;

SELECT
    a.ACCIDENT_NO,
    a.ROAD_NAME,
    rsc.SURFACE_COND_DESC AS ROAD_SURFACE
FROM Accident AS a
JOIN Surface_Cond_Seq AS scs
    ON a.ACCIDENT_NO = scs.ACCIDENT_NO
JOIN Road_Surface_Cond AS rsc
    ON scs.SURFACE_COND = rsc.SURFACE_COND
LIMIT 20;

SELECT
    a.ACCIDENT_NO,
    a.ROAD_NAME,
    a.SPEED_ZONE,
    lc.COND_NAME AS LIGHT_CONDITION,
    ac.ATMOSPH_COND_DESC AS AMOSPHERIC_CONDITION,
    rsc.SURFACE_COND_DESC AS ROAD_SURFACE
FROM Accident AS a
JOIN Light_Condition AS lc
    ON a.LIGHT_CONDITION = lc.COND_ID
JOIN Atmospheric_Cond_Seq AS acs
    ON a.ACCIDENT_NO = acs.ACCIDENT_NO
JOIN Amospheric_Cond AS ac
    ON acs.ATMOSPH_COND = ac.ATMOSPH_COND
JOIN Surface_Cond_Seq AS scs
    ON a.ACCIDENT_NO = scs.ACCIDENT_NO
JOIN Road_Surface_Cond AS rsc
    ON scs.SURFACE_COND = rsc.SURFACE_COND
LIMIT 30;


SELECT
    ac.ATMOSPH_COND_DESC AS ATMOSPHERIC_CONDITION,
    lc.COND_NAME AS LIGHT_CONDITION,
    rsc.SURFACE_COND_DESC AS ROAD_SURFACE,
    COUNT(DISTINCT a.ACCIDENT_NO) AS TOTAL_CRASHES
FROM Accident AS a
JOIN Light_Condition AS lc
    ON a.LIGHT_CONDITION = lc.COND_ID
JOIN Atmospheric_Cond_Seq AS acs
    ON a.ACCIDENT_NO = acs.ACCIDENT_NO
JOIN Amospheric_Cond AS ac
    ON acs.ATMOSPH_COND = ac.ATMOSPH_COND
JOIN Surface_Cond_Seq AS scs
    ON a.ACCIDENT_NO = scs.ACCIDENT_NO
JOIN Road_Surface_Cond AS rsc
    ON scs.SURFACE_COND = rsc.SURFACE_COND
GROUP BY
    ac.ATMOSPH_COND_DESC,
    lc.COND_NAME,
    rsc.SURFACE_COND_DESC
ORDER BY TOTAL_CRASHES DESC;

SELECT
    ac.ATMOSPH_COND_DESC AS ATMOSPHERIC_CONDITION,
    lc.COND_NAME AS LIGHT_CONDITION,
    rsc.SURFACE_COND_DESC AS ROAD_SURFACE,
    COUNT(DISTINCT a.ACCIDENT_NO) AS TOTAL_CRASHES
FROM Accident AS a
JOIN Light_Condition AS lc
    ON a.LIGHT_CONDITION = lc.COND_ID
JOIN Atmospheric_Cond_Seq AS acs
    ON a.ACCIDENT_NO = acs.ACCIDENT_NO
JOIN Amospheric_Cond AS ac
    ON acs.ATMOSPH_COND = ac.ATMOSPH_COND
JOIN Surface_Cond_Seq AS scs
    ON a.ACCIDENT_NO = scs.ACCIDENT_NO
JOIN Road_Surface_Cond AS rsc
    ON scs.SURFACE_COND = rsc.SURFACE_COND
GROUP BY
    ac.ATMOSPH_COND_DESC,
    lc.COND_NAME,
    rsc.SURFACE_COND_DESC
ORDER BY TOTAL_CRASHES DESC;

SELECT *
FROM Amospheric_Cond;

SELECT *
FROM Light_Condition;

SELECT *
FROM Road_Surface_Cond;